import React from 'react';
import { type StyleProp, type ViewStyle, type ImageStyle, type TextStyle } from 'react-native';
export interface MonthYearPickerProps {
    initialDate?: Date;
    minDate?: Date;
    maxDate?: Date;
    placeholder?: string;
    onChange?: (date: Date | string) => void;
    disabled?: boolean;
    styleInput?: StyleProp<ViewStyle>;
    disabledCancel?: boolean;
    disabledConfirm?: boolean;
    maxDateSelect?: Date;
    textError?: string;
    isShowError?: boolean;
    months?: Record<string, string>;
    dateFormat?: string;
    modalTitle?: string;
    cancelButtonText?: string;
    confirmButtonText?: string;
    inputBackgroundColor?: string;
    inputTextColor?: string;
    inputBorderColor?: string;
    inputBorderWidth?: number;
    disabledBackgroundColor?: string;
    modalBackgroundColor?: string;
    titleTextColor?: string;
    selectedTextColor?: string;
    unselectedTextColor?: string;
    highlightBorderColor?: string;
    buttonBackgroundColor?: string;
    disabledButtonColor?: string;
    errorTextColor?: string;
    lineIndicatorColor?: string;
    styleModal?: StyleProp<ViewStyle>;
    styleModalContainer?: StyleProp<ViewStyle>;
    stylePickerContainer?: StyleProp<ViewStyle>;
    styleTitle?: StyleProp<ViewStyle>;
    styleContentContainer?: StyleProp<ViewStyle>;
    styleScrollView?: StyleProp<ViewStyle>;
    styleOptionText?: StyleProp<ViewStyle>;
    styleSelectedText?: StyleProp<ViewStyle>;
    styleHighlightBox?: StyleProp<ViewStyle>;
    styleButtonContainer?: StyleProp<ViewStyle>;
    styleButton?: StyleProp<ViewStyle>;
    styleCancelButton?: StyleProp<ViewStyle>;
    styleConfirmButton?: StyleProp<ViewStyle>;
    styleErrorText?: StyleProp<ViewStyle>;
    styleInputText?: StyleProp<ViewStyle>;
    styleLineIndicator?: StyleProp<ViewStyle>;
    styleButtonTextCancel?: StyleProp<TextStyle>;
    styleButtonTextConfirm?: StyleProp<TextStyle>;
    itemHeight?: number;
    visibleItems?: number;
    borderRadius?: number;
    inputPadding?: number;
    iconCalendar?: any;
    iconCalendarStyle?: StyleProp<ImageStyle>;
    showIcon?: boolean;
    backdropOpacity?: number;
    animationInTiming?: number;
    animationOutTiming?: number;
    onOpen?: () => void;
    onClose?: () => void;
    onBackdropPress?: () => void;
}
declare const MonthYearPicker: React.FC<MonthYearPickerProps>;
export default MonthYearPicker;
//# sourceMappingURL=monthYearPicker.d.ts.map